version: '3'
services:
  web:
    image: odoo:16.0
    container_name: odoo16_learn_web
    env_file: .env
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./custom_addons:/mnt/custom-addons
  db:
    image: postgres:14
    container_name: odoo16_learn_db
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata

volumes:
  web-data:
  db-data: