version: '3.6'

services:
  uat_web:
    image: odoo16:16.20230101
    build:
      context: ./odoo-docker
      network: host
    container_name: odoo16_learn_web
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD_FILE=/run/secrets/password
    user: odoo
    volumes:
      - web_data:/var/lib/odoo
      - $PWD/addons:/mnt/extra-addons
    secrets:
      - password
    working_dir: /var/lib/odoo
    restart: always
    ports:
      - 8079:8069
      - 8082:8072
    volumes:
      - web_data:/var/lib/odoo
      - $PWD/odoo.prod.conf:/etc/odoo/odoo.conf
      - $PWD/addons:/mnt/extra-addons
    command: ["odoo", "--proxy-mode", "-d", "${DB:-}", "-u", "${UPDATE:-base}"]

networks:
  default:
    external:
      name: odoo16_learn_net

volumes:
  web_data:

secrets:
  password:
    file: $PWD/secret
